server:
  port: 8082

spring:
  application:
    name: login-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/login-service
      auto-index-creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2024_7_onlineChar
    username: root
    password: 1234567890
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xfvape.uid.worker.entity


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 123456
  expiration: 86400
  refreshExpiration: 604800